<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Roxana Zaman" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least onez should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<p>This dataset involves information on female crabs and whether they will have male crabs acting as satellites around them. The variables color and spine are categorical variables that determine the color and type of spine that the female crabs will have. The width and weight variables are numeric variables that are measured in cm and grams, respectively. The satell variable reports the number of satellite crabs around the female crab and the y variable is a binary variable that explains whether the female crab has satellites or not. There are 173 female crabs being measured.</p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>library(lmtest)
library(dplyr)
library(plotROC)

data &lt;- read.csv(&#39;horseshoecrab.csv&#39;)
data$has_sat &lt;- ifelse(data$y == 1, &#39;yes&#39;, &#39;no&#39;)

crab_manova &lt;- manova(cbind(weight, width)~ has_sat, data = data)

summary(crab_manova)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## has_sat 1 0.16569 16.88 2 170 2.056e-07 ***
## Residuals 171
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(crab_manova)</code></pre>
<pre><code>## Response weight :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## has_sat 1 8585671 8585671 30.157 1.421e-07 ***
## Residuals 171 48683122 284697
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response width :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## has_sat 1 123.28 123.276 32.845 4.415e-08 ***
## Residuals 171 641.80 3.753
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(data$weight, data$has_sat, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  data$weight and data$has_sat 
## 
##     no     
## yes 1.4e-07
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(data$width, data$has_sat, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  data$width and data$has_sat 
## 
##     no     
## yes 4.4e-08
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>alpha &lt;- .05 / 5
alpha</code></pre>
<pre><code>## [1] 0.01</code></pre>
<pre class="r"><code>library(rstatix)
ggplot(data, aes(x = width, y = weight)) +
geom_point(alpha = .5) + geom_density_2d()  + facet_wrap(~has_sat)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-1-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>group &lt;- data$has_sat
DVs &lt;- data %&gt;% select(weight, width)
sapply(split(DVs,group), mshapiro_test)</code></pre>
<pre><code>##           no           yes         
## statistic 0.785857     0.9317528   
## p.value   4.222585e-08 2.535145e-05</code></pre>
<pre class="r"><code>box_m(DVs, group)</code></pre>
<pre><code>## # A tibble: 1 x 4
## statistic p.value parameter method
## &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
## 1 12.9 0.00483 3 Box&#39;s M-test for Homogeneity of
Covariance Matrices</code></pre>
<p>I performed 5 tests in all - one manova, 2 one-way anovas, and 2 pairwise t-tests. I initally set alpha to be .05, and it was reduced to .01 after the Bonferroni correction. Based on the manova test, I found a significant difference in mean for either weight or width based on whether the crabs had satellites. Both weight and width were found to be significantly different based on the existence of a satellite crab.</p>
<p>After running a shapiro test on the groups, it appears that the multivariate normality assumption may be violated, though the density plots do not look too far off. In addition, the BoxM test implied that the assumption of homogeneity of variance-covariance matrices could also be violated. There do appear to be some outliers in the data as well, implying that MANOVA may not have been an appropriate analysis technique.</p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>mean(data$weight[data$has_sat == &#39;yes&#39;]) - mean(data$weight[data$has_sat == &#39;no&#39;])</code></pre>
<pre><code>## [1] 464.5718</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
  new&lt;-data.frame(weight=sample(data$weight),has_sat=data$has_sat)
  rand_dist[i]&lt;-mean(new[new$has_sat==&quot;yes&quot;,]$weight)-
  mean(new[new$has_sat==&quot;no&quot;,]$weight)}

mean(rand_dist&gt; 464.5718 | rand_dist &lt; -464.5718)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;, xlim = c(-500, 500)); abline(v = c(-464.5718, 464.5718),col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>I performed a randomization test on the mean difference in weight based on whether the crabs had a satellite.
Ho: Mean weight is the same for whether the crab has satellites or not
Ha: Mean weight differs for crabs that have satellite crabs and crabs that don’t have satellites.</p>
<p>It appears that there is a significant difference in the mean weight of crabs that do have satellites and crabs that do not based on my p-value that is approximately 0.</p>
<ul>
<li><p><strong>3. (40 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code> using geom_smooth(method=“lm”). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the <code>interactions</code> package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (10)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (5)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (10)</li>
</ul></li>
</ul>
<pre class="r"><code>data$weight_c &lt;- data$weight - mean(data$weight)
crab_lm &lt;- lm(width ~ has_sat * weight_c, data = data)
summary(crab_lm)</code></pre>
<pre><code>##
## Call:
## lm(formula = width ~ has_sat * weight_c, data = data)
##
## Residuals:
## Min 1Q Median 3Q Max
## -3.3693 -0.6180 -0.0077 0.5548 3.6527
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 2.599e+01 1.478e-01 175.875 &lt;2e-16 ***
## has_satyes 3.907e-01 1.760e-01 2.220 0.0278 *
## weight_c 2.767e-03 2.760e-04 10.025 &lt;2e-16 ***
## has_satyes:weight_c 5.049e-04 3.192e-04 1.582 0.1155
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 0.9667 on 169 degrees of
freedom
## Multiple R-squared: 0.7936, Adjusted R-squared: 0.7899
## F-statistic: 216.5 on 3 and 169 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>crab_lm$coefficients[2] + crab_lm$coefficients[4]</code></pre>
<pre><code>## has_satyes 
##  0.3912186</code></pre>
<pre class="r"><code>crab_lm$coefficients[3] + crab_lm$coefficients[4]</code></pre>
<pre><code>##    weight_c 
## 0.003272178</code></pre>
<pre class="r"><code>ggplot(data, aes(weight,width, color = has_sat)) + geom_smooth(aes(group=data$has_sat), method = &quot;lm&quot;, se = F, fullrange = T) +
geom_point()+geom_vline(xintercept=0,lty=2)+geom_vline(xintercept=mean(data$weight))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids&lt;-crab_lm$residuals
fitvals&lt;-crab_lm$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>qqnorm(resids)
qqline(resids)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(sandwich)

coeftest(crab_lm, vcov = vcovHC(crab_lm))[,1:2] </code></pre>
<pre><code>##                         Estimate   Std. Error
## (Intercept)         2.599422e+01 0.1233518818
## has_satyes          3.907137e-01 0.1474365357
## weight_c            2.767275e-03 0.0005008621
## has_satyes:weight_c 5.049035e-04 0.0005459352</code></pre>
<p>The intercept is difficult to interpret, as it is not possible for a crab to have 0 weight.</p>
<p>While controling for weight, a crab that has a satellite is predicted to be .3912186 cm wider than a crab that does not have a satellite.</p>
<p>While controlling for whether a crab has a satellite, for every increase in 1 gram of weight, the width will be expected to increase by .003272178 cm.</p>
<p>The model explains 78.99% of the variablility in the data.</p>
<p>Based on the residual plot, the data appears to be linear and homoskedatic, as the points surrounding the line at 0 seem to have equal spread and continue forward in a linear fashion.</p>
<p>The data appears to be somewhat normal, as the qqplot shows that much of the data follows the qqplot. However, there is a large degree of spread for the points of data far from the mean.</p>
<p>The robust standard errors are very similar to the standard errors from the linear regression model, as the data is roughly homoskedastic.</p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
  boot_dat&lt;-data[sample(nrow(data),replace=TRUE),]
  fit&lt;-lm(width ~ has_sat * weight_c, data = boot_dat)
  coef(fit)
})

## Estimated SEs
samp_distn%&gt;%t%&gt;%as.data.frame %&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) has_satyes     weight_c has_satyes:weight_c
## 1   0.1290908  0.1514385 0.0004806072        0.0005139229</code></pre>
<p>The bootstrap standard errors are very similar to both the standard errors calculated using a linear model and the robust standard errors, implying that p-values will be approximately the same.</p>
<ul>
<li><p><strong>5. (30 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (5)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code>crab_log &lt;- glm(y ~ width + weight, data = data, family = binomial)
summary(crab_log)</code></pre>
<pre><code>##
## Call:
## glm(formula = y ~ width + weight, family = binomial,
data = data)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -2.1127 -1.0344 0.5304 0.9006 1.7207
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -9.3547261 3.5280465 -2.652 0.00801 **
## width 0.3067892 0.1819473 1.686 0.09177 .
## weight 0.0008338 0.0006716 1.241 0.21445
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 225.76 on 172 degrees of freedom
## Residual deviance: 192.89 on 170 degrees of freedom
## AIC: 198.89
##
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp(crab_log$coefficients[2])</code></pre>
<pre><code>##    width 
## 1.359054</code></pre>
<pre class="r"><code>exp(crab_log$coefficients[3])</code></pre>
<pre><code>##   weight 
## 1.000834</code></pre>
<pre class="r"><code>probabilities = predict(crab_log, type = &quot;response&quot;)
table(actual = data$y, predicted = as.numeric(probabilities &gt; 0.5))</code></pre>
<pre><code>##       predicted
## actual  0  1
##      0 28 34
##      1 16 95</code></pre>
<pre class="r"><code>print(&quot;Accuracy&quot;)</code></pre>
<pre><code>## [1] &quot;Accuracy&quot;</code></pre>
<pre class="r"><code>123 / 173</code></pre>
<pre><code>## [1] 0.7109827</code></pre>
<pre class="r"><code>print(&quot;Sensitivity&quot;)</code></pre>
<pre><code>## [1] &quot;Sensitivity&quot;</code></pre>
<pre class="r"><code>95 / 111</code></pre>
<pre><code>## [1] 0.8558559</code></pre>
<pre class="r"><code>print(&quot;Specificity&quot;)</code></pre>
<pre><code>## [1] &quot;Specificity&quot;</code></pre>
<pre class="r"><code>28 / 62</code></pre>
<pre><code>## [1] 0.4516129</code></pre>
<pre class="r"><code>myplot &lt;- ggplot(data) + geom_roc(aes(d = y, m = probabilities))
print(&quot;AUC&quot;)</code></pre>
<pre><code>## [1] &quot;AUC&quot;</code></pre>
<pre class="r"><code>calc_auc(myplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.7493461</code></pre>
<pre class="r"><code>data$logit &lt;- predict(crab_log, type = &quot;link&quot;)

data %&gt;% ggplot() + geom_density(aes(logit, color=has_sat, fill=has_sat), alpha = .4) + theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>myplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-2.png" width="768" style="display: block; margin: auto;" />
While controlling for weight, for every increase in 1 cm of the shell width the odds of a female crab having a satellite crab increases multiplicatvely by 1.314232.</p>
<p>While controlling for shell width, for every increase in 1 gram of the weight of the crab the odds of a femable crab having a satellite crab increases multiplicatively by 1.000795.</p>
<p>The model predicts 71.09827% of the crabs correctly for whether they will have a satellite crab.</p>
<p>The model correctly predicts positive results for a crab having satellite crabs 85.58559% of the time.</p>
<p>The model correctly predicts negative results for a crab having satellite crabs 45.16129% of the time.</p>
<p>The area under the curve for the ROC plot is .7493461, implying that the model is a fair classifier.</p>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model’s out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
<pre class="r"><code>crab_log &lt;- glm(y ~ width + weight + color + spine, data = data, family = binomial)

probabilities = predict(crab_log, type = &quot;response&quot;)
table(actual = data$y, predicted = as.numeric(probabilities &gt; 0.5))</code></pre>
<pre><code>##       predicted
## actual  0  1
##      0 31 31
##      1 16 95</code></pre>
<pre class="r"><code>print(&quot;Accuracy&quot;)</code></pre>
<pre><code>## [1] &quot;Accuracy&quot;</code></pre>
<pre class="r"><code>126 / 173</code></pre>
<pre><code>## [1] 0.7283237</code></pre>
<pre class="r"><code>print(&quot;Sensitivity&quot;)</code></pre>
<pre><code>## [1] &quot;Sensitivity&quot;</code></pre>
<pre class="r"><code>95 / 111</code></pre>
<pre><code>## [1] 0.8558559</code></pre>
<pre class="r"><code>print(&quot;Specificity&quot;)</code></pre>
<pre><code>## [1] &quot;Specificity&quot;</code></pre>
<pre class="r"><code>31 / 62</code></pre>
<pre><code>## [1] 0.5</code></pre>
<pre class="r"><code>myplot &lt;- ggplot(data) + geom_roc(aes(d = y, m = probabilities))
print(&quot;AUC&quot;)</code></pre>
<pre><code>## [1] &quot;AUC&quot;</code></pre>
<pre class="r"><code>calc_auc(myplot)</code></pre>
<pre><code>##   PANEL group      AUC
## 1     1    -1 0.770125</code></pre>
<pre class="r"><code>library(pROC)


class_diag &lt;- function(probs,truth){
  if(is.character(truth)==TRUE) truth&lt;-as.factor(truth)
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),factor(truth, levels=c(0,1)))
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth))
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) ) 
  data.frame(acc,sens,spec,ppv,f1,auc)}


k=10 #choose number of folds
data2&lt;-data[sample(nrow(data)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(data)),breaks=k,labels=F) #create folds
diags&lt;-NULL
for(i in 1:k){
  ## Create training and test sets
  train&lt;-data2[folds!=i,]
  test&lt;-data2[folds==i,]
  truth&lt;-test$y ## Truth labels for fold i
  ## Train model on training set (all but fold i)
  fit&lt;-glm(y ~ width + weight + color + spine, data = data, family = binomial)
  ## Test model on test set (fold i)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  ## Get diagnostics for fold i
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.7287582 0.8572439 0.4833333 0.752634 0.7969256
0.7468543</code></pre>
<pre class="r"><code>X = model.matrix(y~width + weight + color + spine, data)[,-1]
y = data$y
library(glmnet)
cv&lt;-cv.glmnet(X,y,family=&quot;binomial&quot;)
lasso&lt;-glmnet(X,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 5 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept) -3.190182e+00
## width        1.377536e-01
## weight       6.776028e-05
## color        .           
## spine        .</code></pre>
<pre class="r"><code>k=10 #choose number of folds
data2&lt;-data[sample(nrow(data)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(data)),breaks=k,labels=F) #create folds
diags&lt;-NULL
for(i in 1:k){
  ## Create training and test sets
  train&lt;-data2[folds!=i,]
  test&lt;-data2[folds==i,]
  truth&lt;-test$y ## Truth labels for fold i
  ## Train model on training set (all but fold i)
  fit&lt;-glm(y ~ width + weight + color, data = data, family = binomial)
  ## Test model on test set (fold i)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  ## Get diagnostics for fold i
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.7166667 0.8578419 0.489127 0.7498035 0.7920776
0.7927127</code></pre>
<p>The initial model predicts 72.83237% of the crabs correctly for whether they will have a satellite crab.</p>
<p>The initial model correctly predicts positive results for a crab having satellite crabs 85.58559% of the time.</p>
<p>The initial model correctly predicts negative results for a crab having satellite crabs 50% of the time.</p>
<p>The area under the curve for the ROC plot with the initial model is .770125, implying that our model is a fair classifier.</p>
<p>The area under the curve for the new ROC plot based on one rendition of 10-fold cross validation is .777793, implying that our model is a fair classifer and is similar quality to the previous model.</p>
<p>For the lasso model, the width, weight, and color are retained for classifying whether a crab will have a satellite crab.</p>
<p>The new area under the curve with the new model is .7634173 based on one rendition of 10-fold cross validation, which is less than that of the previous model. However, the values are very similar so the classifiers are of similar quality.</p>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages("fivethirtyeight"),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
